const C=window.CONFIG;
const programs=[
["un-cafe-con-aroma-de-fe","Un café con aroma de fe","Conversaciones, encuentros y reflexiones desde la fe."],
["el-podcast","El Podcast","Conversaciones para escuchar, pensar y vivir el Evangelio."],
["el-youcat-te-conecta","El Youcat te conecta","Formación juvenil y Catecismo."],
["la-voz-lider","La voz líder","Historias, liderazgo y servicio."],
["hagan-lo-que-el-les-diga","Hagan lo que Él les diga","Reflexiones desde la Palabra y María."],
["una-palabra-en-60-segundos","Una palabra en 60 segundos","Un mensaje breve para la vida diaria."],
["fe-y-vida-diaria","Fe y vida diaria","La fe aplicada a los desafíos de cada día."],
["la-santa-misa","La Santa Misa","Contenido para acompañar y profundizar en la Eucaristía."],
["kerigma-en-fuego","Kerigma en fuego","Anuncio de Jesucristo vivo."],
["semilla-vocacional","Semilla vocacional","Historias para descubrir la llamada de Dios."],
["cultiva-la-fe","Cultiva la fe","Recursos para crecer espiritualmente."]
];
const routes=[
["#/","Inicio"],["#/noticias","Iglesia al día"],["#/programas","Programas"],["#/en-vivo","🔴 En vivo"],
["#/64-datos","64 datos"],["#/diocesis","Diócesis"],["#/editorial","Editorial"],["#/quienes-somos","Quiénes somos"],["#/admin","Admin"]
];
function header(){
 return `<div class="topbar"><div class="wrap"><span>Jóvenes Influencers del Señor · Medio católico de la Diócesis de Ocaña</span><span class="toplinks"><a href="#/quienes-somos">Quiénes somos</a><a href="#/editorial">Editorial</a></span></div></div><header class="channel-nav"><div class="wrap nav"><a class="brand" href="#/"><img src="${C.logo}" alt="Logo Jóvenes Influencers del Señor"><span class="brand-text">Jóvenes Influencers<br><small>del Señor</small></span></a><nav id="menu" class="menu">${routes.map(r=>`<a href="${r[0]}" class="${r[0]==='#/en-vivo'?'live-pill':''}">${r[1]}</a>`).join("")}</nav><button class="hamb" aria-label="Menú" onclick="document.getElementById('menu').classList.toggle('open')">☰</button></div></header>`;
}
function footer(){return `<footer><div class="wrap foot"><div><div class="foot-brand"><img src="${C.logo}" alt="Logo"><div><strong>Jóvenes Influencers del Señor</strong><br><small>Medio de comunicación católico</small></div></div><p>Informamos, formamos y evangelizamos desde la Diócesis de Ocaña.</p><div class="footer-social"><a class="social" href="#" aria-label="Facebook">f</a><a class="social" href="#" aria-label="YouTube">▶</a><a class="social" href="#" aria-label="Instagram">◎</a></div></div><div><strong>Contenido</strong><a href="#/noticias">Iglesia al día</a><a href="#/programas">Programas</a><a href="#/en-vivo">Señal en vivo</a><a href="#/64-datos">64 datos históricos</a></div><div><strong>La Iglesia</strong><a href="#/diocesis">Diócesis de Ocaña</a><a href="#/quienes-somos">Quiénes somos</a><a href="#/editorial">Editorial</a><a href="#/admin">Administración</a></div></div><div class="wrap creator">Sitio web creado por <b>Gamarra TV</b></div><div class="copy">© ${new Date().getFullYear()} Jóvenes Influencers del Señor · Diócesis de Ocaña</div></footer>`}
function layout(title,tag,content){return header()+`<div class="head"><div class="wrap"><span class="tag">${tag}</span><h1>${title}</h1></div></div>${content}`+footer()}
function yt(url){if(!url)return "";try{let u=new URL(url),id=u.searchParams.get("v")||u.pathname.split("/").pop();return id?`<div class="video"><iframe src="https://www.youtube.com/embed/${id}" allowfullscreen loading="lazy"></iframe></div>`:""}catch(e){return""}}
function date(v){return v?new Date(v).toLocaleDateString("es-CO",{day:"2-digit",month:"long",year:"numeric"}):""}
function home(){return `<div class="hero hero-tv"><div class="wrap hero-grid"><div class="hero-copy"><span class="eyebrow">✝ Canal y medio de comunicación católico</span><h1>Jóvenes Influencers del Señor</h1><p>La voz joven de la Iglesia en el mundo digital. Noticias, espiritualidad, formación, programas y transmisiones desde la Diócesis de Ocaña.</p><a class="btn red" href="#/en-vivo">🔴 SEÑAL EN VIVO</a><a class="btn" href="#/programas">▶ NUESTRA PROGRAMACIÓN</a></div><div><img class="hero-logo" src="${C.logo}" alt="Jóvenes Influencers del Señor"><p style="text-align:center;color:var(--purple);font-weight:800">Una Iglesia que comunica y evangeliza</p></div></div></div>

<section class="breaking"><div class="wrap breaking-in"><b>ACTUALIDAD</b><span>Información y vida de la Iglesia</span><a href="#/noticias">Ver noticias →</a></div></section>

<section><div class="wrap"><div class="section-top"><div><span class="tag">Actualidad</span><h2>Noticias de la Iglesia</h2><p>Noticias diocesanas, nacionales e internacionales.</p></div><a class="btn light" href="#/noticias">Ver todas</a></div><div class="news-grid"><article class="news-main"><div class="news-main-image">📰</div><div class="news-main-body"><span class="tag">Iglesia al día</span><h2>La actualidad de nuestra Iglesia</h2><p>Un espacio informativo para conocer los acontecimientos de la Diócesis de Ocaña y las noticias que marcan la vida de la Iglesia.</p><a class="btn" href="#/noticias">Entrar a Iglesia al día →</a></div></article><div class="news-side"><div class="card"><span class="tag">Diócesis</span><h3>Noticias diocesanas</h3><p>Celebraciones, comunidades, parroquias y acontecimientos.</p></div><div class="card"><span class="tag">Iglesia universal</span><h3>Noticias nacionales e internacionales</h3><p>Información para estar conectados con la Iglesia.</p></div></div></div></div></section>

<section class="live-home"><div class="wrap live-box"><div class="live"><div class="live-screen"><div><h2><span class="dot"></span>SEÑAL EN VIVO</h2><p>Acompaña nuestras transmisiones.</p></div></div></div><div class="live-info"><span class="tag" style="color:#e2bce9">Ahora en pantalla</span><h2>Jóvenes Influencers del Señor</h2><p>Transmisiones de celebraciones, eventos y contenidos especiales.</p><a class="btn red" href="#/en-vivo">Ver señal completa →</a></div></div></section>

<section class="program-section"><div class="wrap"><div class="section-top"><div><span class="tag">Programación</span><h2>Programas destacados</h2><p>Producciones propias para acompañarte en la fe.</p></div><a class="btn light" href="#/programas">Toda la programación</a></div><div class="poster-grid">${programs.slice(0,8).map((p,i)=>`<a class="poster" href="#/programas/${p[0]}"><div class="poster-top">▶</div><div class="poster-body"><span class="program-number">${String(i+1).padStart(2,"0")}</span><h3>${p[1]}</h3><p>${p[2]}</p><small>Ver programa →</small></div></a>`).join("")}</div></div></section>

<section><div class="wrap"><div class="section-top"><div><span class="tag">Especial de octubre</span><h2>64 datos históricos</h2><p>Un recorrido audiovisual por la historia de nuestra Diócesis.</p></div><a class="btn light" href="#/64-datos">Ver especial</a></div><div class="history-banner"><img src="${C.logo64}" alt="64 años"><div><span class="tag">Sección temporal</span><h2>64 datos, 64 momentos de historia y fe</h2><p>Durante todo octubre presentamos un dato histórico acompañado de video.</p><a class="btn" href="#/64-datos">Conocer el especial →</a></div></div></div></section>

<div class="quote-band"><h2>“Comunicar también es una manera de anunciar la Buena Noticia.”</h2><p>Jóvenes Influencers del Señor · Diócesis de Ocaña</p></div>

<section><div class="wrap"><div class="section-top"><div><span class="tag">Conoce nuestro medio</span><h2>Una Iglesia cercana y digital</h2><p>Historia, parroquias, advocaciones, integrantes y contenidos para crecer en la fe.</p></div></div><div class="grid"><a class="card" href="#/diocesis"><h3>⛪ Diócesis de Ocaña</h3><p>Historia, parroquias y advocaciones marianas.</p></a><a class="card" href="#/editorial"><h3>✍️ Editorial</h3><p>Reflexiones y escritos sobre temas importantes.</p></a><a class="card" href="#/quienes-somos"><h3>👥 Quiénes somos</h3><p>Conoce a quienes hacen posible esta misión.</p></a></div></div></section>`}
async function noticias(){let c=`<section><div class="wrap" id="news"><div class="empty">Cargando noticias...</div></div></section>`;render(layout("Iglesia al día","Noticias y videos",c));try{const {createClient}=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");let s=createClient(C.supabaseUrl,C.supabaseKey),r=await s.from("news").select("*").eq("published",true).order("published_at",{ascending:false});document.getElementById("news").innerHTML=r.data?.length?r.data.map(n=>`<article class="article"><small>${date(n.published_at)}</small><h2>${n.title}</h2><p>${n.excerpt||""}</p>${yt(n.youtube_url)}${n.facebook_url?`<a class="btn light" target="_blank" href="${n.facebook_url}">Ver en Facebook</a>`:""}<p>${n.content||""}</p></article>`).join(""):'<div class="empty"><h3>Aún no hay noticias</h3><p>Publícalas desde el panel administrativo.</p></div>'}catch(e){document.getElementById("news").innerHTML='<div class="notice">Configura Supabase y ejecuta supabase.sql para cargar noticias.</div>'}}
function programas(){return layout("Nuestros programas","Espacios audiovisuales",`<section><div class="wrap"><p class="intro">Todos nuestros programas son de video y están pensados para evangelizar y acompañar.</p><div class="grid">${programs.map((p,i)=>`<a class="card program" href="#/programas/${p[0]}"><div><span class="tag">${String(i+1).padStart(2,"0")}</span><h3>${p[1]}</h3><p>${p[2]}</p></div><span class="btn light">Ver programa</span></a>`).join("")}</div></div></section>`)}
function programa(slug){let p=programs.find(x=>x[0]===slug);return layout(p?p[1]:"Programa","Programa audiovisual",`<section><div class="wrap"><div class="article"><h2>${p?p[1]:"Programa"}</h2><p>${p?p[2]:"Contenido audiovisual de Jóvenes Influencers del Señor."}</p><div class="notice">Los episodios y videos de este programa podrán publicarse desde el panel administrativo.</div></div></div></section>`)}
function live(){return layout("Señal en vivo","Transmisión",`<section><div class="wrap"><div class="live"><div id="live" class="live-screen"><div><h2><span class="dot"></span>Señal en vivo</h2><p>Configura tu URL .m3u8 en <b>config.js</b> para activar la señal.</p></div></div></div></div></section>`)}
function history(){return layout("64 datos históricos","Especial de octubre de 2026",`<section><div class="wrap"><div class="article"><img class="logo64" src="${C.logo64}"><h2>64 datos históricos de la Diócesis de Ocaña</h2><p>Sección temporal activa durante octubre de 2026. Cada dato puede incluir su video.</p></div><div class="notice">Los 64 datos se administrarán desde Supabase.</div></div></section>`)}
function diocesis(){return layout("Diócesis de Ocaña","Historia, parroquias y advocaciones",`<section><div class="wrap"><div class="grid"><div class="card"><h3>Historia</h3><p>Espacio para presentar la historia de la Diócesis de Ocaña.</p></div><div class="card"><h3>Parroquias</h3><p>Directorio de todas las parroquias de la diócesis.</p></div><div class="card"><h3>Advocaciones marianas</h3><p>Conoce las advocaciones marianas.</p></div></div></div></section>`)}
function editorial(){return layout("Editorial","Escritos y reflexiones",`<section><div class="wrap"><div class="empty">Aquí aparecerán los escritos y temas importantes publicados desde el panel administrativo.</div></div></section>`)}
function quienes(){return layout("Quiénes somos","Equipo y misión",`<section><div class="wrap"><div class="article"><h2>Una misión de evangelización digital</h2><p>Jóvenes Influencers del Señor es un medio de comunicación católico de la Diócesis de Ocaña dedicado a informar, formar y evangelizar.</p><p>Aquí estará la historia del proyecto, la misión y la presentación de todos sus integrantes.</p></div><div class="empty">Los integrantes se cargarán desde Supabase.</div></div></section>`)}
function admin(){return layout("Panel administrativo","Gestión del sitio",`<section><div class="wrap" style="max-width:850px"><div class="article"><h2>Administración</h2><p>Desde aquí se gestionarán noticias, videos, 64 datos, editoriales, integrantes, parroquias y advocaciones.</p><div class="notice">La conexión de administración se habilita con Supabase Auth y la tabla <b>admins</b>.</div></div></div></section>`)}
function render(html){document.getElementById("app").innerHTML=html;window.scrollTo(0,0);let h=location.hash;document.querySelectorAll(".menu a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")===h||(!h&&a.getAttribute("href")==="#/"))); }
async function router(){let path=(location.hash||"#/").replace(/^#\/?/,"").replace(/\/$/,"");let parts=path.split("/").filter(Boolean);if(!parts.length)return render(home());if(parts[0]==="noticias")return noticias();if(parts[0]==="programas")return parts[1]?render(programa(parts[1])):render(programas());if(parts[0]==="en-vivo")return render(live());if(parts[0]==="64-datos")return render(history());if(parts[0]==="diocesis")return render(diocesis());if(parts[0]==="editorial")return render(editorial());if(parts[0]==="quienes-somos")return render(quienes());if(parts[0]==="admin")return render(admin());return render(home())}
window.addEventListener("hashchange",router);router();
