const C=window.CONFIG;
const programs=[
["un-cafe-con-aroma-de-fe","Un café con aroma de fe","Conversaciones, encuentros y reflexiones desde la fe."],
["el-podcast","El Podcast","Conversaciones para escuchar, pensar y vivir el Evangelio."],
["el-youcat-te-conecta","El Youcat te conecta","Formación juvenil y Catecismo."],
["la-voz-lider","La voz líder","Historias, liderazgo y servicio."],
["hagan-lo-que-el-les-diga","Hagan lo que Él les diga","Reflexiones desde la Palabra y María."],
["una-palabra-en-60-segundos","Una palabra en 60 segundos","Un mensaje breve para la vida diaria."],
["fe-y-vida-diaria","Fe y vida diaria","La fe aplicada a los desafíos de cada día."],
["la-santa-misa","La Santa Misa","Contenido para acompañar y profundizar en la Eucaristía."],
["kerigma-en-fuego","Kerigma en fuego","Anuncio de Jesucristo vivo."],
["semilla-vocacional","Semilla vocacional","Historias para descubrir la llamada de Dios."],
["cultiva-la-fe","Cultiva la fe","Recursos para crecer espiritualmente."]
];
const routes=[
["#/","Inicio"],["#/noticias","Iglesia al día"],["#/programas","Programas"],["#/en-vivo","🔴 En vivo"],
["#/64-datos","64 datos"],["#/diocesis","Diócesis"],["#/editorial","Editorial"],["#/quienes-somos","Quiénes somos"],["#/admin","Admin"]
];
function header(){
 return `<header><div class="wrap nav"><a class="brand" href="#/"><img src="${C.logo}" alt="Logo"><span>Jóvenes Influencers<br><small>del Señor</small></span></a><nav id="menu" class="menu">${routes.map(r=>`<a href="${r[0]}">${r[1]}</a>`).join("")}</nav><button class="hamb" onclick="document.getElementById('menu').classList.toggle('open')">☰</button></div></header>`;
}
function footer(){return `<footer><div class="wrap foot"><div><strong>Jóvenes Influencers del Señor</strong><p>Medio de comunicación católico de la Diócesis de Ocaña.</p></div><div><strong>Secciones</strong><a href="#/noticias">Iglesia al día</a><a href="#/programas">Programas</a><a href="#/en-vivo">Señal en vivo</a></div><div><strong>Información</strong><a href="#/diocesis">Diócesis de Ocaña</a><a href="#/quienes-somos">Quiénes somos</a><a href="#/editorial">Editorial</a></div></div><div class="copy">© ${new Date().getFullYear()} Jóvenes Influencers del Señor</div></footer>`}
function layout(title,tag,content){return header()+`<div class="head"><div class="wrap"><span class="tag">${tag}</span><h1>${title}</h1></div></div>${content}`+footer()}
function yt(url){if(!url)return "";try{let u=new URL(url),id=u.searchParams.get("v")||u.pathname.split("/").pop();return id?`<div class="video"><iframe src="https://www.youtube.com/embed/${id}" allowfullscreen loading="lazy"></iframe></div>`:""}catch(e){return""}}
function date(v){return v?new Date(v).toLocaleDateString("es-CO",{day:"2-digit",month:"long",year:"numeric"}):""}
function home(){return `<div class="hero"><div class="wrap hero-grid"><div><span class="tag">Medio de comunicación católico · Diócesis de Ocaña</span><h1>Jóvenes Influencers del Señor</h1><p>Comunicar, formar y evangelizar en el mundo digital.</p><a class="btn red" href="#/en-vivo">🔴 Señal en vivo</a><a class="btn light" href="#/noticias">Iglesia al día</a></div><img class="hero-logo" src="${C.logo}" alt="Logo"></div></div><section><div class="wrap"><h2>Todo en un solo lugar</h2><p class="intro">Noticias, videos, programas, formación, historia de la Diócesis de Ocaña y evangelización.</p><div class="grid">
<a class="card" href="#/noticias"><h3>📰 Iglesia al día</h3><p>Noticias y videos diocesanos, nacionales e internacionales.</p></a>
<a class="card" href="#/programas"><h3>🎥 Programas</h3><p>Conoce nuestros 11 programas audiovisuales.</p></a>
<a class="card" href="#/64-datos"><h3>🕊️ 64 datos históricos</h3><p>Especial temporal durante octubre de 2026.</p></a>
<a class="card" href="#/diocesis"><h3>⛪ Diócesis de Ocaña</h3><p>Historia, parroquias y advocaciones marianas.</p></a>
<a class="card" href="#/editorial"><h3>✍️ Editorial</h3><p>Escritos y reflexiones sobre temas importantes.</p></a>
<a class="card" href="#/quienes-somos"><h3>👥 Quiénes somos</h3><p>Conoce a nuestros integrantes y nuestra misión.</p></a>
</div></div></section>`}
async function noticias(){let c=`<section><div class="wrap" id="news"><div class="empty">Cargando noticias...</div></div></section>`;render(layout("Iglesia al día","Noticias y videos",c));try{const {createClient}=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");let s=createClient(C.supabaseUrl,C.supabaseKey),r=await s.from("news").select("*").eq("published",true).order("published_at",{ascending:false});document.getElementById("news").innerHTML=r.data?.length?r.data.map(n=>`<article class="article"><small>${date(n.published_at)}</small><h2>${n.title}</h2><p>${n.excerpt||""}</p>${yt(n.youtube_url)}${n.facebook_url?`<a class="btn light" target="_blank" href="${n.facebook_url}">Ver en Facebook</a>`:""}<p>${n.content||""}</p></article>`).join(""):'<div class="empty"><h3>Aún no hay noticias</h3><p>Publícalas desde el panel administrativo.</p></div>'}catch(e){document.getElementById("news").innerHTML='<div class="notice">Configura Supabase y ejecuta supabase.sql para cargar noticias.</div>'}}
function programas(){return layout("Nuestros programas","Espacios audiovisuales",`<section><div class="wrap"><p class="intro">Todos nuestros programas son de video y están pensados para evangelizar y acompañar.</p><div class="grid">${programs.map((p,i)=>`<a class="card program" href="#/programas/${p[0]}"><div><span class="tag">${String(i+1).padStart(2,"0")}</span><h3>${p[1]}</h3><p>${p[2]}</p></div><span class="btn light">Ver programa</span></a>`).join("")}</div></div></section>`)}
function programa(slug){let p=programs.find(x=>x[0]===slug);return layout(p?p[1]:"Programa","Programa audiovisual",`<section><div class="wrap"><div class="article"><h2>${p?p[1]:"Programa"}</h2><p>${p?p[2]:"Contenido audiovisual de Jóvenes Influencers del Señor."}</p><div class="notice">Los episodios y videos de este programa podrán publicarse desde el panel administrativo.</div></div></div></section>`)}
function live(){return layout("Señal en vivo","Transmisión",`<section><div class="wrap"><div class="live"><div id="live" class="live-screen"><div><h2><span class="dot"></span>Señal en vivo</h2><p>Configura tu URL .m3u8 en <b>config.js</b> para activar la señal.</p></div></div></div></div></section>`)}
function history(){return layout("64 datos históricos","Especial de octubre de 2026",`<section><div class="wrap"><div class="article"><img class="logo64" src="${C.logo64}"><h2>64 datos históricos de la Diócesis de Ocaña</h2><p>Sección temporal activa durante octubre de 2026. Cada dato puede incluir su video.</p></div><div class="notice">Los 64 datos se administrarán desde Supabase.</div></div></section>`)}
function diocesis(){return layout("Diócesis de Ocaña","Historia, parroquias y advocaciones",`<section><div class="wrap"><div class="grid"><div class="card"><h3>Historia</h3><p>Espacio para presentar la historia de la Diócesis de Ocaña.</p></div><div class="card"><h3>Parroquias</h3><p>Directorio de todas las parroquias de la diócesis.</p></div><div class="card"><h3>Advocaciones marianas</h3><p>Conoce las advocaciones marianas.</p></div></div></div></section>`)}
function editorial(){return layout("Editorial","Escritos y reflexiones",`<section><div class="wrap"><div class="empty">Aquí aparecerán los escritos y temas importantes publicados desde el panel administrativo.</div></div></section>`)}
function quienes(){return layout("Quiénes somos","Equipo y misión",`<section><div class="wrap"><div class="article"><h2>Una misión de evangelización digital</h2><p>Jóvenes Influencers del Señor es un medio de comunicación católico de la Diócesis de Ocaña dedicado a informar, formar y evangelizar.</p><p>Aquí estará la historia del proyecto, la misión y la presentación de todos sus integrantes.</p></div><div class="empty">Los integrantes se cargarán desde Supabase.</div></div></section>`)}
function admin(){return layout("Panel administrativo","Gestión del sitio",`<section><div class="wrap" style="max-width:850px"><div class="article"><h2>Administración</h2><p>Desde aquí se gestionarán noticias, videos, 64 datos, editoriales, integrantes, parroquias y advocaciones.</p><div class="notice">La conexión de administración se habilita con Supabase Auth y la tabla <b>admins</b>.</div></div></div></section>`)}
function render(html){document.getElementById("app").innerHTML=html;window.scrollTo(0,0);let h=location.hash;document.querySelectorAll(".menu a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")===h||(!h&&a.getAttribute("href")==="#/"))); }
async function router(){let path=(location.hash||"#/").replace(/^#\/?/,"").replace(/\/$/,"");let parts=path.split("/").filter(Boolean);if(!parts.length)return render(home());if(parts[0]==="noticias")return noticias();if(parts[0]==="programas")return parts[1]?render(programa(parts[1])):render(programas());if(parts[0]==="en-vivo")return render(live());if(parts[0]==="64-datos")return render(history());if(parts[0]==="diocesis")return render(diocesis());if(parts[0]==="editorial")return render(editorial());if(parts[0]==="quienes-somos")return render(quienes());if(parts[0]==="admin")return render(admin());return render(home())}
window.addEventListener("hashchange",router);router();
