(function(){
  const cfg=window.JIS_CONFIG||{};
  const sb=window.supabase;
  const client=(sb&&window.SUPABASE_URL&&window.SUPABASE_PUBLISHABLE_KEY)?sb.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY):null;
  window.jisSupabase=client;
  const nav=[['Inicio','/'],['Iglesia al Día','/iglesia-al-dia/'],['Programas','/programas/'],['En Vivo','/en-vivo/'],['64 Datos','/64-datos/'],['Diócesis','/diocesis/'],['Editorial','/editorial/'],['Quiénes somos','/quienes-somos/']];
  function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
  function header(){const path=location.pathname;return `<header class="header"><div class="container bar"><a class="brand" href="/"><img src="${cfg.logo}" alt="${esc(cfg.siteName)}"><span>Jóvenes Influencers<br><small>del Señor</small></span></a><button class="menu" id="menuBtn">☰</button><nav class="nav" id="nav">${nav.map(([n,u])=>`<a href="${u}">${n}</a>`).join('')}<a class="login" href="/admin/">🔐 Iniciar sesión</a></nav></div></header>`}
  function footer(){return `<footer class="footer"><div class="container footer-inner"><img src="${cfg.logo}" alt="Logo"><div><strong>${esc(cfg.siteName)}</strong><p>${esc(cfg.siteDescription)}</p><div class="creator">Creado por Gamarra TV</div></div></div></footer>`}
  function mount(){const site=document.getElementById('site');if(site){site.innerHTML=header()+footer();const b=document.getElementById('menuBtn');if(b)b.onclick=()=>document.getElementById('nav').classList.toggle('open');}}
  async function liveData(){if(!client)return {data:null,error:new Error('Supabase no está configurado')};const r=await client.from('live_streams').select('*').eq('active',true).eq('show_live',true).order('created_at',{ascending:false}).limit(1).maybeSingle();return r}
  function player(row){if(!row)return '<div class="notice">En este momento no hay una transmisión activa.</div>';let body='';const type=(row.type||'').toLowerCase();const url=row.url||row.loop_url||'';if(type==='m3u8'||/\.m3u8($|\?)/i.test(url)){body=`<video id="hls-player" class="live-player" controls autoplay playsinline></video><script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script><script>(function(){const v=document.getElementById('hls-player'),u=${JSON.stringify(url)};if(window.Hls&&Hls.isSupported()){const h=new Hls();h.loadSource(u);h.attachMedia(v);}else{v.src=u;}})();</script>`}else if(type==='youtube'){const id=(url.match(/(?:youtu\.be\/|v=|embed\/)([^&?/]+)/)||[])[1];body=`<div class="live-player"><iframe src="https://www.youtube.com/embed/${id||''}?autoplay=1" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>`}else if(type==='facebook'){body=`<div class="live-player"><iframe src="https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(url)}&show_text=false&autoplay=true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowfullscreen></iframe></div>`}else if(row.loop_url){body=`<div class="live-player"><video src="${esc(row.loop_url)}" autoplay muted loop playsinline controls></video></div>`}else{body=`<div class="live-player"><a class="btn" target="_blank" rel="noopener" href="${esc(url)}">Abrir transmisión</a></div>`}return `<div class="live-card"><div style="display:flex;justify-content:space-between;gap:15px;align-items:center"><div><span class="badge">🔴 EN VIVO</span><h2>${esc(row.title||'Transmisión en vivo')}</h2></div></div>${body}<p>${esc(row.description||'Acompáñanos en nuestra transmisión.')}</p></div>`}
  window.renderHomeLive=async function(id){const el=document.getElementById(id);if(!el)return;const {data,error}=await liveData();el.innerHTML=error?`<div class="error">No se pudo consultar la señal: ${esc(error.message)}</div>`:player(data)};
  window.renderLivePage=async function(id){const el=document.getElementById(id);if(!el)return;const {data,error}=await liveData();el.innerHTML=error?`<div class="error">No se pudo consultar la señal. Verifica la tabla <b>live_streams</b> en Supabase.<br>${esc(error.message)}</div>`:player(data)};
  window.loadNews=async function(id){const el=document.getElementById(id);if(!el||!client)return;const {data,error}=await client.from('news').select('*').eq('published',true).order('published_at',{ascending:false}).order('created_at',{ascending:false});if(error){el.innerHTML=`<div class="error">${esc(error.message)}</div>`;return}el.innerHTML=(data||[]).map(n=>`<article class="article">${n.image_url?`<img src="${esc(n.image_url)}" alt="">`:''}<div class="article-body"><small class="muted">${esc(n.category||'Iglesia al Día')}</small><h3>${esc(n.title)}</h3><p>${esc(n.summary||n.content||'')}</p>${n.youtube_url?`<a class="btn small" target="_blank" href="${esc(n.youtube_url)}">Ver video</a>`:''}</div></article>`).join('')||'<div class="notice">Aún no hay noticias publicadas.</div>'}
  window.loadPrograms=async function(id){const el=document.getElementById(id);if(!el||!client)return;const {data,error}=await client.from('programs').select('*').eq('visible',true).order('sort_order').order('name');if(error){el.innerHTML=`<div class="error">${esc(error.message)}</div>`;return}el.innerHTML=(data||[]).map(p=>`<a class="card" href="/programas/?programa=${encodeURIComponent(p.slug)}">${p.image_url?`<img src="${esc(p.image_url)}" class="preview" alt="">`:''}<h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p></a>`).join('')||'<div class="notice">No hay programas publicados.</div>'}
  window.loadProgramDetail=async function(id){const el=document.getElementById(id);if(!el||!client)return;const slug=new URLSearchParams(location.search).get('programa');if(!slug){return loadPrograms(id)}const {data:p,error}=await client.from('programs').select('*').eq('slug',slug).maybeSingle();if(error||!p){el.innerHTML='<div class="notice">Programa no encontrado.</div>';return}const r=await client.from('episodes').select('*').eq('program_id',p.id).eq('published',true).order('sort_order').order('published_at',{ascending:false});el.innerHTML=`<div class="article-body"><h2>${esc(p.name)}</h2><p>${esc(p.description||'')}</p></div><div class="content-grid">${(r.data||[]).map(e=>`<article class="article"><div class="article-body"><h3>${esc(e.title)}</h3><p>${esc(e.description||'')}</p>${e.youtube_url?`<a class="btn small" target="_blank" href="${esc(e.youtube_url)}">YouTube</a>`:''}${e.facebook_url?` <a class="btn small" target="_blank" href="${esc(e.facebook_url)}">Facebook</a>`:''}</div></article>`).join('')||'<div class="notice">Aún no hay episodios publicados.</div>'}</div>`}
  window.load64=async function(id){const el=document.getElementById(id);if(!el||!client)return;const {data,error}=await client.from('historical_64').select('*').eq('published',true).order('number');if(error){el.innerHTML=`<div class="error">${esc(error.message)}</div>`;return}el.innerHTML=(data||[]).map(x=>`<article class="article"><div class="article-body"><small class="muted">Dato ${x.number}</small><h3>${esc(x.title)}</h3><p>${esc(x.content||'')}</p>${x.image_url?`<img src="${esc(x.image_url)}" class="preview" alt="">`:''}${x.video_url?`<p><a class="btn small" target="_blank" href="${esc(x.video_url)}">Ver video</a></p>`:''}</div></article>`).join('')||'<div class="notice">No hay datos publicados.</div>'}
  window.loadSection=async function(table,id){const el=document.getElementById(id);if(!el||!client)return;const {data,error}=await client.from(table).select('*').eq('published',true).order('sort_order').order('created_at',{ascending:false});if(error){el.innerHTML=`<div class="error">${esc(error.message)}</div>`;return}el.innerHTML=(data||[]).map(x=>`<article class="article">${x.image_url?`<img src="${esc(x.image_url)}" alt="">`:''}<div class="article-body"><h3>${esc(x.title||x.name)}</h3><p>${esc(x.content||x.description||x.bio||'')}</p>${x.social_url?`<a class="btn small" target="_blank" href="${esc(x.social_url)}">Red social</a>`:''}</div></article>`).join('')||'<div class="notice">Aún no hay contenido publicado.</div>'}
  mount();
})();
