
const C=window.JIS_CONFIG||{};
function shell(title,content){document.title=title+" | Jóvenes Influencers del Señor";return `<header class="header"><div class="container bar"><a class="brand" href="/"><img src="${C.logo}" alt="Jóvenes Influencers del Señor"><span>Jóvenes Influencers<br><small>del Señor</small></span></a><button class="menu" id="menuBtn">☰</button><nav class="nav" id="nav"><a href="/">Inicio</a><a href="/iglesia-al-dia/">Iglesia al Día</a><a href="/programas/">Programas</a><a href="/en-vivo/">En Vivo</a><a href="/64-datos/">64 Datos</a><a href="/diocesis/">Diócesis</a><a href="/editorial/">Editorial</a><a href="/quienes-somos/">Quiénes somos</a></nav></div></header><main>${content}</main><footer><div class="container footer"><img src="${C.logo}" alt="Logo"><div><strong>Jóvenes Influencers del Señor</strong><p>Comunicación al servicio de Dios.</p><p>Medio de comunicación católico de la Diócesis de Ocaña.</p></div></div><div class="created">Sitio web creado por <b>Gamarra TV</b></div></footer>`}
function embed(url){if(!url)return "";let u=url;if(url.includes("youtube.com/watch?v="))u="https://www.youtube.com/embed/"+url.split("v=")[1].split("&")[0];if(url.includes("youtu.be/"))u="https://www.youtube.com/embed/"+url.split("youtu.be/")[1].split("?")[0];return `<div class="video"><iframe src="${u}" allowfullscreen loading="lazy"></iframe></div>`}
function supabaseClient(){return window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY)}
document.addEventListener("DOMContentLoaded",()=>{const b=document.getElementById("menuBtn");if(b)b.onclick=()=>document.getElementById("nav").classList.toggle("open")});

async function getLiveStream(){
  if(!window.supabase) return null;
  try{const sb=supabaseClient(); const {data}=await sb.from('live_streams').select('*').eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle(); return data||null}catch(e){console.warn('live_streams:',e);return null}
}
function facebookEmbed(url){if(!url)return '';return `<div class="video live-facebook"><iframe src="https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(url)}&show_text=false&width=1280" scrolling="no" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowfullscreen></iframe></div>`}
async function renderLiveBlock(targetId='liveBlock', compact=false){const el=document.getElementById(targetId);if(!el)return;const live=await getLiveStream();if(live){el.innerHTML=`<div class="live-card"><div class="live-card-head"><span class="live-badge"><span class="dot"></span> EN VIVO</span><span>${live.title||'Jóvenes Influencers del Señor'}</span></div>${live.facebook_url?facebookEmbed(live.facebook_url):''}<div class="live-card-body"><h2>${live.title||'Jóvenes Influencers del Señor'}</h2>${live.description?`<p>${live.description}</p>`:''}<a class="btn live" target="_blank" rel="noopener" href="${live.facebook_url||'https://www.facebook.com/jovenesinfluencersdelsenor'}">Ver en Facebook</a></div></div>`}else{el.innerHTML=`<div class="live-off"><div class="live-off-icon">📺</div><h2>Actualmente no estamos transmitiendo</h2><p>Cuando comience una transmisión en Facebook, aparecerá aquí.</p><a class="btn" target="_blank" rel="noopener" href="https://www.facebook.com/jovenesinfluencersdelsenor">Visitar Facebook</a></div>`}}
