-- ================================================================
-- REPARACIÓN DEFINITIVA: public.about_us
-- Ejecutar completo en Supabase > SQL Editor.
-- No elimina ni modifica team_members (Integrantes).
-- ================================================================

create table if not exists public.about_us (
  id bigint generated by default as identity primary key,
  title text not null default 'Quiénes somos',
  content text not null default '',
  mission text,
  vision text,
  image_url text,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Asegura que las columnas existan si la tabla fue creada anteriormente
-- con una versión incompleta.
alter table public.about_us add column if not exists title text;
alter table public.about_us add column if not exists content text;
alter table public.about_us add column if not exists mission text;
alter table public.about_us add column if not exists vision text;
alter table public.about_us add column if not exists image_url text;
alter table public.about_us add column if not exists published boolean;
alter table public.about_us add column if not exists created_at timestamptz;
alter table public.about_us add column if not exists updated_at timestamptz;

-- Valores seguros para filas existentes.
update public.about_us
set title = coalesce(title, 'Quiénes somos'),
    content = coalesce(content, ''),
    published = coalesce(published, true),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

alter table public.about_us alter column title set default 'Quiénes somos';
alter table public.about_us alter column content set default '';
alter table public.about_us alter column published set default true;
alter table public.about_us alter column created_at set default now();
alter table public.about_us alter column updated_at set default now();

alter table public.about_us enable row level security;

drop policy if exists about_us_public_select on public.about_us;
drop policy if exists about_us_admin_all on public.about_us;

create policy about_us_public_select
on public.about_us
for select
to anon, authenticated
using (published = true);

create policy about_us_admin_all
on public.about_us
for all
to authenticated
using (
  exists (
    select 1
    from public.admins
    where public.admins.id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.admins
    where public.admins.id = auth.uid()
  )
);

-- Permisos explícitos para PostgREST/Supabase.
grant usage on schema public to anon, authenticated;
grant select on public.about_us to anon, authenticated;
grant insert, update, delete on public.about_us to authenticated;

-- Registro inicial si no existe ninguno.
insert into public.about_us (title, content, mission, vision, published)
select 'Quiénes somos', '', '', '', true
where not exists (select 1 from public.about_us);

-- Recargar el schema cache de PostgREST.
notify pgrst, 'reload schema';

-- Comprobación final: debe devolver al menos una fila.
select id, title, published from public.about_us order by id limit 10;
