-- =========================================================
-- REPARACIÓN DEFINITIVA: QUIÉNES SOMOS
-- Crea public.about_us si todavía no existe.
-- No borra ni modifica team_members.
-- =========================================================

create table if not exists public.about_us (
  id bigint generated by default as identity primary key,
  title text not null default 'Quiénes somos',
  content text not null default '',
  mission text,
  vision text,
  image_url text,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.about_us enable row level security;

drop policy if exists about_us_public_select on public.about_us;
drop policy if exists about_us_admin_all on public.about_us;

create policy about_us_public_select
on public.about_us
for select
to anon, authenticated
using (published = true);

create policy about_us_admin_all
on public.about_us
for all
to authenticated
using (
  exists (
    select 1
    from public.admins
    where public.admins.id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.admins
    where public.admins.id = auth.uid()
  )
);

-- Crear el registro inicial solamente si la tabla está vacía.
insert into public.about_us (title, content, mission, vision, image_url, published)
select
  'Quiénes somos',
  '',
  '',
  '',
  null,
  true
where not exists (
  select 1 from public.about_us
);

notify pgrst, 'reload schema';
