CREATE TABLE IF NOT EXISTS public.about_us (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,title text NOT NULL DEFAULT 'Quiénes somos',content text NOT NULL DEFAULT '',mission text,vision text,image_url text,published boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.about_us ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS about_us_public_select ON public.about_us;
DROP POLICY IF EXISTS about_us_admin_all ON public.about_us;
CREATE POLICY about_us_public_select ON public.about_us FOR SELECT TO anon, authenticated USING (published = true);
CREATE POLICY about_us_admin_all ON public.about_us FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.admins WHERE admins.id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM public.admins WHERE admins.id = auth.uid()));
NOTIFY pgrst, 'reload schema';
