-- Ejecutar en Supabase SQL Editor.
-- NO uses INSERT INTO (...) literalmente: debes escribir las columnas reales.
-- Esta versión crea/ajusta una tabla compatible con el reproductor.

create table if not exists public.live_streams (
  id bigint generated by default as identity primary key,
  title text,
  type text default 'm3u8',
  url text,
  image_url text,
  loop_url text,
  show_live boolean default false,
  show_live_page boolean default false,
  active boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.live_streams add column if not exists title text;
alter table public.live_streams add column if not exists type text default 'm3u8';
alter table public.live_streams add column if not exists url text;
alter table public.live_streams add column if not exists image_url text;
alter table public.live_streams add column if not exists loop_url text;
alter table public.live_streams add column if not exists show_live boolean default false;
alter table public.live_streams add column if not exists show_live_page boolean default false;
alter table public.live_streams add column if not exists active boolean default false;

alter table public.live_streams enable row level security;

drop policy if exists "live_streams_public_read" on public.live_streams;
create policy "live_streams_public_read"
on public.live_streams for select
to anon, authenticated
using (true);

-- Después de ejecutar, en el panel puedes usar una fila como:
-- INSERT INTO public.live_streams
-- (title,type,url,show_live,show_live_page,active)
-- VALUES
-- ('Señal en vivo','m3u8','https://TU-URL/index.m3u8',true,true,true);

-- Si ya tienes una fila, puedes actualizarla:
-- UPDATE public.live_streams
-- SET title='Señal en vivo',
--     type='m3u8',
--     url='https://TU-URL/index.m3u8',
--     show_live=true,
--     show_live_page=true,
--     active=true
-- WHERE id=1;
