const SUPABASE_URL = process.env.SUPABASE_URL || 'https://sqawhmimfcwnvkeviznk.supabase.co';
const SUPABASE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY || 'sb_publishable_IpEAQRQ7To6ONqG6MyWuuA_DM630ufy';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function absoluteUrl(req,p){const host=req.headers.host;const proto=req.headers['x-forwarded-proto']||'https';return `${proto}://${host}${p}`}
function strip(v=''){return String(v).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function truncate(v='',n=180){const s=strip(v);return s.length>n?s.slice(0,n-1).trimEnd()+'…':s}
export default async function handler(req,res){
 try{
  const slug=String(req.query.slug||'').trim(); if(!slug)return res.status(400).send('Falta el identificador de la editorial.');
  const endpoint=`${SUPABASE_URL}/rest/v1/editorials?select=*&published=eq.true&slug=eq.${encodeURIComponent(slug)}&limit=1`;
  const response=await fetch(endpoint,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}}); if(!response.ok)throw new Error(`Supabase respondió ${response.status}`);
  const rows=await response.json(); const editorial=rows&&rows[0]; if(!editorial)return res.status(404).send('Editorial no encontrada.');
  const title=editorial.title||'Editorial'; const description=truncate(editorial.excerpt||editorial.summary||editorial.content||'Editorial de Jóvenes Influencers del Señor.');
  const image=editorial.image_url||absoluteUrl(req,'https://i.ibb.co/hF3t07Lt/IMG-7484.png'); const canonical=absoluteUrl(req,`/editoriales/editorial/${encodeURIComponent(editorial.slug||slug)}`);
  const published=editorial.published_at||editorial.created_at; const date=published?new Date(published).toLocaleDateString('es-CO',{day:'2-digit',month:'long',year:'numeric'}):'';
  const author=editorial.author_name||editorial.author||'Redacción'; const position=editorial.author_position||''; const authorPhoto=editorial.author_photo_url||'';
  const content=editorial.content||''; const safeContent=/<[^>]+>/.test(content)?content:`<p>${esc(content).replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>')}</p>`;
  res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, s-maxage=60, stale-while-revalidate=300');
  return res.status(200).send(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Editorial | Jóvenes Influencers del Señor</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="article"><meta property="og:site_name" content="Jóvenes Influencers del Señor"><meta property="og:locale" content="es_CO"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="${esc(image)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(image)}"><link rel="icon" href="https://i.ibb.co/hF3t07Lt/IMG-7484.png"><link rel="stylesheet" href="/estilos.css"><style>
.article-page{max-width:1080px;margin:48px auto;padding:0 18px 80px}.article-card{background:#fff;border:1px solid #e7dfd2;border-radius:26px;overflow:hidden;box-shadow:0 15px 45px rgba(48,33,22,.1)}.article-cover{width:100%;max-height:650px;object-fit:cover;display:block;background:#eee}.article-body{padding:38px}.article-body h1{font-size:clamp(34px,5vw,60px);line-height:1.03;margin:10px 0 15px}.article-meta{color:#756b62;font-size:14px;margin-bottom:30px}.article-content{font-size:19px;line-height:1.9;color:#493d34}.article-content p{margin:0 0 20px}.article-content img{max-width:100%;height:auto;border-radius:14px}.author-box{margin-top:38px;padding:22px 0;border-top:1px solid #e7dfd2;display:flex;align-items:center;gap:15px}.author-box img,.author-placeholder{width:76px;height:76px;border-radius:50%;object-fit:cover;background:#f0eaf3;display:grid;place-items:center;font-size:30px}.author-box strong,.author-box span{display:block}.author-box span{color:#756b62;margin-top:4px}.article-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:28px}.article-actions a{display:inline-flex;padding:12px 18px;border-radius:999px;background:#21180f;color:#fff;text-decoration:none;font-weight:800}.article-actions a.alt{background:#fff;color:#21180f;border:1px solid #e7dfd2}@media(max-width:650px){.article-page{margin:20px auto;padding-bottom:50px}.article-body{padding:24px 20px}.article-content{font-size:17px;line-height:1.8}.author-box{align-items:flex-start}.article-actions a{width:100%;justify-content:center}}
</style></head><body><header class="header"><div class="container bar"><a class="brand" href="/"><img src="https://i.ibb.co/hF3t07Lt/IMG-7484.png" alt="Logo"><span>Jóvenes Influencers<br><small>del Señor</small></span></a><button class="menu" id="menuBtn" type="button" aria-label="Abrir menú" aria-controls="nav" aria-expanded="false"><span></span><span></span><span></span></button><nav class="nav" id="nav" aria-label="Navegación principal"><a href="/">Inicio</a><a href="/iglesia-al-dia/">Iglesia al Día</a><a href="/programas/">Programas</a><a href="/en-vivo/">En Vivo</a><a href="/editorial/">Editorial</a><a href="/quienes-somos/">Quiénes somos</a></nav></div></header><main class="article-page"><article class="article-card">${image?`<img class="article-cover" src="${esc(image)}" alt="${esc(title)}">`:''}<div class="article-body"><span class="tag">EDITORIAL</span><h1>${esc(title)}</h1><div class="article-meta">${date?`Publicado el <b>${esc(date)}</b>`:''}</div><div class="article-content">${safeContent}</div><div class="author-box">${authorPhoto?`<img src="${esc(authorPhoto)}" alt="${esc(author)}">`:'<div class="author-placeholder">✍️</div>'}<div><strong>${esc(author)}</strong>${position?`<span>${esc(position)}</span>`:''}</div></div><div class="article-actions"><a target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(canonical)}">Compartir en Facebook</a><a class="alt" href="/editorial/">← Volver a Editorial</a></div></div></article></main><footer><div class="container footer"><img src="https://i.ibb.co/hF3t07Lt/IMG-7484.png" alt="Logo"><div class="footer-center"><strong>Jóvenes Influencers del Señor</strong><p>Comunicación al servicio de Dios.</p><p>© ${new Date().getFullYear()} Jóvenes Influencers del Señor</p><div class="footer-creator">Creado por <b>Gamarra TV</b></div></div></div></footer><script src="/common.js"></script></body></html>`)
 }catch(e){console.error(e);return res.status(500).send('No fue posible cargar la editorial.')}
}
